[project]
name = "legal-citation-bert"
version = "0.1.0"
description = ""
authors = [
    {name = "Samier", email = "samier_saeed@protonmail.com"},
]
dependencies = [
    "typer>=0.12.3",
    "transformers[torch]>=4.40.1",
    "wasabi>=1.1.2",
    "nltk>=3.8.1",
    "pydantic>=2.6.4",
    "datasets>=2.18.0",
    "polars>=0.20.17",
    "scikit-learn>=1.4.1.post1",
    "numpy>=1.26.4",
    "torch>=2.3.0",
    "pandas>=2.2.1",
    "python-dotenv>=1.0.1",
    "mistralai>=0.1.8",
    "outlines>=0.0.39",
    "openai>=1.23.2",
    "tiktoken>=0.6.0",
    "pyright>=1.1.360",
    "eyecite>=2.6.3",
    "pytest>=8.1.2",
    "regex>=2024.4.16",
    "beartype>=0.18.5",
    "pymupdf>=1.24.5",
    "more-itertools>=10.3.0",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.options]
add = ["--global", "--project", "."]
